### ISSUE TITLE
Calculate the inference time of each model

### ISSUE THREAD

**Issue by SonNguyen2510** [tucan9389/PoseEstimation-TFLiteSwift#93]
Dear author,
May I ask you how to calculate the inference (the inference time and pose process time) time of each 3D human pose model as you showed?
Thank you so much!

**Comment by tucan9389** [comment]
@SonNguyen2510 
I think there is no implementation to measure the inference time in this repo. 
But you can check [this another repo's Measure.swift](https://github.com/tucan9389/PoseEstimation-CoreML/blob/master/PoseEstimation-CoreML/Measure.swift) and, use it or implement it yourself.

I have usually used the `CACurrentMediaTime` of CoreAnimation Framework rather than `NSTimer`, etc. because of the performance.
Here is the reason: https://stackoverflow.com/questions/11660403/nstimer-vs-cacurrentmediatime

I hope this is helpful.

**Comment by SonNguyen2510** [comment]
@tucan9389  So can you tell me how can you get these numbers? Did you use the "CACurrentMediaTime"? 
![Screenshot from 2023-05-10 21-26-09](https://github.com/tucan9389/PoseEstimation-TFLiteSwift/assets/53286816/0dc50116-085e-4615-9615-63645ef98db1)

**Comment by tucan9389** [comment]
hmmm yeah i think so.
i think i used the Measure.swift in this repo as well but didnt push it (long time ago).

**Comment by SonNguyen2510** [comment]
Thank you for your response

**Comment by tucan9389** [comment]
no problem
